apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service-canary
  namespace: canary
spec:
  type: NodePort
  selector:
    app: train-schedule
    track: canary
  ports:
  - port: 8080
    targetPort: 8080
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment-canary
  namespace: canary
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: train-schedule
      track: canary
  template:
    metadata:
      labels:
        app: train-schedule
        track: canary
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8080
